export const techs = [
    {
        name:"React",
        skill:'Proficient',
        icon:'react',
        size:'lg'
    },
    {
        name:"TypeScript",
        skill:'Proficient',
        icon:'typescript',
        size:'lg'
    },
    {
        name:"Webpack",
        skill:'Intermediate',
        icon:'webpack'
    },
    {
        name:"php",
        skill:'Intermediate',
        icon:'php',
        size:'sm'
    },
    {
        name:"Inkscape",
        skill:'Intermediate',
        icon:'inkscape'
    },
    {
        name:"Figma",
        skill:'Low',
        icon:'figma',
        size:'sm'
    },
    {
        name:"NodeJS",
        skill:'Intermediate',
        icon:'node'
    },
    {
        name:"GraphQL",
        skill:'Intermediate',
        icon:'graphql'
    },
    {
        name:"Scss/Sass",
        skill:'Proficient',
        icon:'sass',
        size:'lg'
    },
]